jobs:
  build:
    docker:
      - image: "circleci/node:4.8.2"
    steps:
      - checkout
      - run: echo "hello world" # run the `echo` command
  test:
    docker:
      - image: "circleci/node:4.8.2"
    steps:
      - checkout
      - run: echo "2nd hello world" # run the `echo` command
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test
